Reduce globals, adding Transport.clock and dropping resetTest
Avoid [1]:

  $ go test -v -race ./...
  ...
  === RUN   TestDontStorePartialRangeInCache
  ==================
  WARNING: DATA RACE
  Write at 0x00c000010e50 by goroutine 23:
    github.com/gregjones/httpcache.TestDontStorePartialRangeInCache()
        /home/travis/gopath/src/github.com/gregjones/httpcache/httpcache_test.go:169 +0x15e
    testing.tRunner()
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:827 +0x162
  Previous read at 0x00c000010e50 by goroutine 22:
    github.com/gregjones/httpcache.(*Transport).RoundTrip.func1()
        /home/travis/gopath/src/github.com/gregjones/httpcache/httpcache.go:275 +0x62
    github.com/gregjones/httpcache.stream.func1()
        /home/travis/gopath/src/github.com/gregjones/httpcache/streamreader.go:64 +0x49
  Goroutine 23 (running) created at:
    testing.(*T).Run()
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:878 +0x650
    testing.runTests.func1()
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:1119 +0xa8
    testing.tRunner()
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:827 +0x162
    testing.runTests()
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:1117 +0x4ee
    testing.(*M).Run()
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:1034 +0x2ee
    github.com/gregjones/httpcache.TestMain()
        /home/travis/gopath/src/github.com/gregjones/httpcache/httpcache_test.go:35 +0x42
    main.main()
        _testmain.go:110 +0x221
  Goroutine 22 (running) created at:
    github.com/gregjones/httpcache.stream()
        /home/travis/gopath/src/github.com/gregjones/httpcache/streamreader.go:63 +0x279
    github.com/gregjones/httpcache.(*Transport).RoundTrip()
        /home/travis/gopath/src/github.com/gregjones/httpcache/httpcache.go:274 +0x644
    net/http.send()
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/http/client.go:250 +0x304
    net/http.(*Client).send()
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/http/client.go:174 +0x1ca
    net/http.(*Client).do()
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/http/client.go:641 +0x531
    net/http.(*Client).Do()
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/http/client.go:509 +0x42
    github.com/gregjones/httpcache.TestDontServeHeadResponseToGetRequest()
        /home/travis/gopath/src/github.com/gregjones/httpcache/httpcache_test.go:247 +0x434
    testing.tRunner()
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:827 +0x162
  ==================
  --- FAIL: TestDontStorePartialRangeInCache (0.00s)
      testing.go:771: race detected during execution of test
  ...

by removing the need to reset the cache and a global clock variable
between tests.  Instead, create a fresh cache for each test (they can
still share the server).  And store the clock in the Transport
structure, where tests that need to set a fake clock can do so without
impacting (or racing against) other tests.

[1]: https://travis-ci.org/gregjones/httpcache/jobs/452675241#L508